// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb1_q1DhXxe19WtFHqNUVRnTdCqnef38Y',
    appId: '1:479753327087:web:6cbe2b4b90a0376132661a',
    messagingSenderId: '479753327087',
    projectId: 'flutter-550bb',
    authDomain: 'flutter-550bb.firebaseapp.com',
    databaseURL: 'https://flutter-550bb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-550bb.firebasestorage.app',
    measurementId: 'G-18EF0B8XES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBre7uWbLwh0mdlyxneX0JbB-7FcT9dihY',
    appId: '1:479753327087:android:07a5bd389cedbe4d32661a',
    messagingSenderId: '479753327087',
    projectId: 'flutter-550bb',
    databaseURL: 'https://flutter-550bb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-550bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfDPq163IRpnCWbUoOq9vPB2h8fLAjC8o',
    appId: '1:479753327087:ios:8ec78efdd6f0fcb332661a',
    messagingSenderId: '479753327087',
    projectId: 'flutter-550bb',
    databaseURL: 'https://flutter-550bb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-550bb.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfDPq163IRpnCWbUoOq9vPB2h8fLAjC8o',
    appId: '1:479753327087:ios:8ec78efdd6f0fcb332661a',
    messagingSenderId: '479753327087',
    projectId: 'flutter-550bb',
    databaseURL: 'https://flutter-550bb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-550bb.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb1_q1DhXxe19WtFHqNUVRnTdCqnef38Y',
    appId: '1:479753327087:web:5afaef653a7988e632661a',
    messagingSenderId: '479753327087',
    projectId: 'flutter-550bb',
    authDomain: 'flutter-550bb.firebaseapp.com',
    databaseURL: 'https://flutter-550bb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-550bb.firebasestorage.app',
    measurementId: 'G-5NGKZP6YV3',
  );
}
